import { createHash } from 'node:crypto';
import type { BoundaryModel, ModuleNode } from '../sensing/boundaries';
import type { ArchitecturalFingerprint } from '../core/types';

/** Repo-relative path of the generated, archon-owned project memory file (M10). */
export const PROJECT_MEMORY_PATH = '.archon/project-memory.md';

/** First line of the file — marks it archon-owned so humans know not to hand-edit it. */
const BANNER = '<!-- archon:generated — DO NOT EDIT; regenerated by `archon init` -->';

/**
 * Project memory generation (M10), "new file only" variant: render the M8
 * structural fingerprint + M9 boundary model into a single project-native
 * markdown file. CLAUDE.md / AGENTS.md (the human contract) are never touched.
 *
 * The output is pure (no I/O): the caller writes it during init, where direct
 * fs is the sanctioned bootstrap exception. A content hash is embedded so
 * regeneration is diff-aware — an unchanged repo rewrites nothing.
 */
export function renderProjectMemory(fp: ArchitecturalFingerprint, model: BoundaryModel): string {
  const lines: string[] = [
    BANNER,
    '',
    '# Project memory',
    '',
    `_Generated from the structural fingerprint (M8) + boundary model (M9). Last scan: ${fp.scannedAt}._`,
    '',
    '## Overview',
    '',
    `- **Layout:** ${fp.layout}${fp.workspaces.length > 0 ? ` (${fp.workspaces.join(', ')})` : ''}`,
    `- **Package manager:** ${fp.packageManager}`,
    `- **Languages:** ${list(fp.languages)}`,
    `- **Build:** ${list(fp.buildSystem)} · **Test:** ${list(fp.testRunners)} · **CI:** ${list(fp.ci)}`,
    `- **Frameworks:** ${list(fp.frameworks)}`,
    `- **Architectural style:** ${fp.architecturalStyle}`,
    `- **Entry points:** ${list(fp.entryPoints)}`,
  ];

  lines.push('', '## Bounded contexts', '');
  if (model.modules.length === 0) {
    lines.push('_No module topology yet — run `archon index`, then `archon init` to refresh._');
  } else {
    lines.push('| Module | Files | In | Out | Instability | Role |', '| --- | --: | --: | --: | --: | --- |');
    for (const m of model.modules) lines.push(row(m));
  }

  if (model.couplingHotspots.length > 0) {
    lines.push('', '## Coupling hotspots', '');
    for (const h of model.couplingHotspots.slice(0, 5)) lines.push(`- \`${h.name}\` — coupling ${h.coupling}`);
  }

  lines.push('', '## God-module candidates', '');
  if (model.godModules.length === 0) lines.push('_None._');
  else for (const g of model.godModules.slice(0, 5)) lines.push(`- \`${g.name}\` — ${g.files} files, coupling ${g.coupling}`);

  lines.push('', '## Circular dependencies', '');
  if (model.cycles.length === 0) lines.push('_None — module graph is acyclic._');
  else for (const c of model.cycles) lines.push(`- ${c.map((n) => `\`${n}\``).join(' → ')} → \`${c[0]}\``);

  const body = lines.join('\n');
  // Trailing marker drives diff-aware regeneration: a matching hash means skip.
  return `${body}\n\n<!-- archon:hash:${contentHash(fp, model)} -->\n`;
}

/**
 * Stable hash of the inputs — embedded in the file so an unchanged repo is a
 * no-op rewrite. Keyed on the fingerprint's `inputHash` (not the whole
 * fingerprint) so the per-scan `scannedAt` timestamp doesn't force a rewrite,
 * matching the basis the fingerprint persist itself uses.
 */
export function contentHash(fp: ArchitecturalFingerprint, model: BoundaryModel): string {
  return createHash('sha256').update(JSON.stringify({ inputHash: fp.inputHash, model })).digest('hex').slice(0, 16);
}

/** The hash a previously-generated file carries, or undefined if absent/unparseable. */
export function extractHash(existing: string): string | undefined {
  return existing.match(/<!-- archon:hash:([0-9a-f]+) -->/)?.[1];
}

const list = (xs: string[]): string => (xs.length > 0 ? xs.join(', ') : '—');

const row = (m: ModuleNode): string =>
  `| \`${m.name}\` | ${m.files} | ${m.fanIn} | ${m.fanOut} | ${m.instability.toFixed(2)} | ${m.role} |`;
